services:
  flight:
    build: .
    ports:
      - "8815:8815"
    volumes:
      - ./data:/data
    environment:
      - PARQUET_FILENAME=${PARQUET_FILENAME:-EURUSD.parquet}
    env_file:
      - .env
